---
title: "ParentsTogether"
author: "Sihong"
date: "3/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r packages, include = FALSE}
library(here)
library(knitr)
library(readr)
library(haven)
library(tidyverse)
```


```{r, echo=FALSE, message = FALSE}
#Define functions
moe.p = function(p, n){
  q = 1-p
  moe = 1.96*sqrt((p*q)/n)
  return(moe)
}

moe.m = function(sd,n){
  moe = 1.96*sd/sqrt(n)
  return(moe)}

combine.cat = function(x, cols, id, newvar.name){
  subset = x[,c(id, "Week", cols)]
  names(subset) = c("id", "Week", paste0("X",1:length(cols)))
  subset = suppressWarnings(gather(subset, "key", "value", -id, -Week))
  subset = filter(subset, !is.na(value))
  subset$key = gsub("X", "", subset$key)
  subset = group_by(subset, id, Week)
  subset = summarise(subset, newvar = paste(key, collapse = ",")) %>% ungroup()
  names(subset) = c(id,"Week", newvar.name)
  x = suppressMessages(full_join(x, subset))
  return(x)
}

find_items = function(string, data2){
  items = names(data2)
  locations = which(grepl(string, items))
  final = items[locations]
  return(final)
}

my.max = function(x) ifelse (!all(is.na(x)), max(x,na.rm = TRUE), NA)
my.min = function(x) ifelse (!all(is.na(x)), min(x,na.rm = TRUE), NA)
```

```{r, echo=FALSE, message = FALSE, warning = FALSE, include=FALSE}
#OR load master data file
master <- read_sav(here("../../../Data Management R3/CC_Clean Survey Data/00_R3 MasterFile/MasterFile_groupings.sav"))

# Remove cases should be excluded
master <- master %>%
  filter ( CaregiverID != "" & is.na(Exclude) == T )

master = master %>%
  group_by(CaregiverID, Week) %>%
  filter(row_number() == max(row_number())) %>%
  ungroup()

total_week <- my.max(master$Week)

#master = master %>%
#  mutate(
#    Week = case_when(
#      Week < 17 ~ Week,
#      Week %% 2 == 0 ~ NA_real_,
#      TRUE ~ Week)
#  ) %>%
#  filter(!is.na(Week))

```

```{r, echo=FALSE, message = FALSE, warning = FALSE}
#Code demographics
master <- master %>%
  mutate (month = case_when(
                  Week == 0 ~ "Pre-COVID",
                  Week >0 & Week <= 4 ~ "April",
                  Week >=5 & Week <=8 ~ "May",
                  Week >=9 & Week <=13 ~ "June",
                  Week >=14 & Week <=17 ~ "July",
                  Week >=18 & Week <=21 ~ "August",
                  Week >=22 & Week <=26 ~ "September",
                  Week >=27 ~ "October"), 
           baseline = case_when (Week - BaselineWeek == 1 ~ 1, 
                                 Week - BaselineWeek > 1 ~ 0))

##Race/ethnicity - 1 = black, 2 = latinx, 3 = white

master <- master %>%
  mutate (RaceGroup = na_if (RaceGroup, 99))%>%
    mutate(
      minority = ifelse(RaceGroup != 5, 1, 0),
      black = ifelse(RaceGroup == 3, 1, 0),
      native = ifelse(RaceGroup == 1, 1, 0),
      asian = ifelse(RaceGroup == 2, 1, 0),
      hawaii = ifelse(RaceGroup == 4, 1, 0),
      white = ifelse(RaceGroup == 5, 1, 0),
      other_race = ifelse(RaceGroup %in% c(6, 7), 1, 0))

master <- master %>%
      mutate(latinx = case_when(
        DEMO.008 == 1 ~ 1,
        DEMO.008 == 0 ~ 0,
        DEMO.008.2 == 0 ~ 0,
        DEMO.008.2 == 1 ~ 1,
        DEMO.008.2 == 2 ~ 1,
        TRUE ~ NA_real_))

master <- master %>%
mutate (race_ethnic = case_when(
      black == 1 ~ "1",
      latinx == 1 ~ "2",
      !is.na(black) ~ "3",
      !is.na(latinx) ~ "3",
      TRUE ~ NA_character_))  

##Povertyline - 0 = high income, 1 = low income
master <- master %>%
  mutate (poverty_cat = FPL.150)

#Material hardship
master <- master %>%
  combine.cat(cols = find_items("FSTR.002_.{1}$", master), 
              id = "CaregiverID",
              newvar.name = "FSTR.002_cat")
  

master <- master %>%
  mutate (diff_pay_food = case_when(
                          FSTR.001 == 0 ~ 0, 
                          grepl("1", FSTR.002_cat) ~ 1,
                          TRUE ~ NA_real_), 
          diff_pay_utilities = case_when(
                          FSTR.001 == 0 ~ 0, 
                          grepl("3", FSTR.002_cat) ~ 1,
                          TRUE ~ NA_real_),
          diff_pay_house = case_when(
                          FSTR.001 == 0 ~ 0, 
                          grepl("2", FSTR.002_cat) ~ 1,
                          TRUE ~ NA_real_),
          diff_pay_healthcare = case_when(
                          FSTR.001 == 0 ~ 0, 
                          grepl("4", FSTR.002_cat) ~ 1,
                          TRUE ~ NA_real_),
          diff_pay_social = case_when(
                          FSTR.001 == 0 ~ 0, 
                          grepl("5", FSTR.002_cat) ~ 1,
                          TRUE ~ NA_real_),
          diff_pay_emotional = case_when(
                          FSTR.001 == 0 ~ 0, 
                          grepl("6", FSTR.002_cat) ~ 1,
                          TRUE ~ NA_real_),
          diff_pay_childcare = case_when(
                          FSTR.001 == 0 ~ 0, 
                          grepl("7", FSTR.002_cat) ~ 1,
                          TRUE ~ NA_real_),
          diff_pay_other = case_when(
                          FSTR.001 == 0 ~ 0, 
                          grepl("8", FSTR.002_cat) ~ 1,
                          TRUE ~ NA_real_))

master <- master %>%
  rowwise() %>%
  mutate(material_hardship = case_when(
    Week == 0 ~ NA_real_,
    TRUE ~ sum(c_across(starts_with("diff_pay_")), na.rm=T))) %>%
  ungroup() %>%
  mutate(num_hardship = material_hardship,
    material_hardship = ifelse(material_hardship > 0, 1, 0)) 

## Children with special needs
master <- combine.cat(x = master, 
                       cols = find_items("HEALTH.005_[0-9]{1}$", master), 
                       id = "CaregiverID",
                       newvar.name = "HEALTH.005_cat")
master <- master %>%
   mutate (disability = case_when (HEALTH.005_1 == 1 ~ 1,
                                   HEALTH.005_2 == 1 ~ 1,
                                   HEALTH.005_3 == 1 ~ 1,
                                   HEALTH.005_4 == 1 ~ 1,
                                   HEALTH.005_5 == 1 ~ 0,
                                   HEALTH.005_6 == 1 ~ 1,
                                   TRUE ~ NA_real_))


## Single parent status
master <- master %>%
  mutate (single = case_when (
                   DEMO.002 %in% c(3,4,5,7,8)~1, 
                   DEMO.011 %in% c(2,4)~1,
                   !is.na(DEMO.002)~0,
                   !is.na(DEMO.011)~0,
                   TRUE ~ NA_real_))
                     
## Employment status
master <- combine.cat (x = master,
                       cols = find_items ("JOB.010_.{1,2}$", master), 
                       id = "CaregiverID",
                       newvar.name = "JOB.010_cat")
  
master$JOB.010_cat = gsub("10", "0", master$JOB.010_cat)
master$working_pre = ifelse (grepl("[1,2,6]", master$JOB.010_cat), 1, 0)
master = combine.cat (x = master,
                       cols = find_items ("JOB.008_.{1,2}$", master), 
                       id = "CaregiverID",
                       newvar.name = "JOB.008_cat")
master$JOB.008_cat = gsub("10", "0", master$JOB.008_cat)
master <- master %>%
  mutate (work_status = case_when(
                        grepl ("1", JOB.008_cat) ~ "1", 
                        grepl ("2", JOB.008_cat) ~ "1", 
                        grepl ("3", JOB.008_cat) ~ "0", 
                        grepl ("4", JOB.008_cat) ~ "0", 
                        grepl ("5", JOB.008_cat) ~ "1", 
                        JOB.008.2 == 1 ~ "1",
                        JOB.008.2 %in% c(2,3) ~ "0",
                        TRUE~NA_character_),
          work_status_pre = case_when(
                        grepl ("1", JOB.010_cat) ~ "1", 
                        grepl ("2", JOB.010_cat) ~ "1", 
                        grepl ("3", JOB.010_cat) ~ "0", 
                        grepl ("4", JOB.010_cat) ~ "0", 
                        grepl ("5", JOB.010_cat) ~ "1", 
                        TRUE~NA_character_))
#1 = stable employed 2 = became unemployed 3 = became employed4 = stable unemployed

# Region
master <- master %>%
  mutate (region = na_if (DEMO.001.b, 5))

# Source
master <- master %>%
  mutate (source_r = case_when (Source == "ParentsTogether" ~ 1, 
                                Source != "ParentsTogether" ~ 0))

#Merge
master_dem <- master %>%
  group_by (CaregiverID) %>%
  summarise (BaselineWeek = my.max (BaselineWeek),
             race_ethnic = my.max(race_ethnic),
             poverty_cat = my.max(poverty_cat),
             material_hardship = my.max(material_hardship),
             disability = my.max (disability),
             single = my.max (single),
             work_status = my.max (work_status),
             work_status_pre = my.max (work_status_pre), 
             region = my.max(region), 
             source_r = my.max (source_r))%>%
  mutate ( ep_change = case_when(
                        work_status == 1 & work_status_pre == 1 ~ "1", 
                        work_status == 1 & work_status_pre == 0 ~ "2", 
                        work_status == 0 & work_status_pre == 1 ~ "3", 
                        work_status == 0 & work_status_pre == 0 ~ "4", 
                        TRUE~NA_character_))%>%
  mutate (race_ethnic = case_when (
                        race_ethnic == 1 ~ "Black", 
                        race_ethnic == 2 ~ "Latinx", 
                        race_ethnic == 3 ~ "White", 
                        TRUE~NA_character_),
          poverty_cat = case_when (
                        poverty_cat == 1 ~ "Low income", 
                        poverty_cat == 0 ~ "High income", 
                        TRUE~NA_character_),
          material_hardship = case_when (
                        material_hardship == 1 ~ "With material hardship", 
                        material_hardship == 0 ~ "Without material hardship", 
                        TRUE~NA_character_),
          disability = case_when (
                        disability == 1 ~ "With disability", 
                        disability == 0 ~ "Without disability", 
                        TRUE~NA_character_),
          single = case_when (
                        single == 1 ~ "Single parent", 
                        single == 0 ~ "Dual parent", 
                        TRUE~NA_character_),
          work_status = case_when (
                        work_status == 1 ~ "Employed", 
                        work_status == 0 ~ "Unemployed", 
                        TRUE~NA_character_),
          work_status_pre = case_when (
                        work_status_pre == 1 ~ "Employed", 
                        work_status_pre == 0 ~ "Unemployed", 
                        TRUE~NA_character_),
          ep_change = case_when (
                        ep_change == 1 ~ "Stable employed", 
                        ep_change == 2 ~ "Became employed", 
                        ep_change == 3 ~ "Became unemployed",
                        ep_change == 4 ~ "Stable unemployed",
                        TRUE~NA_character_), 
          region = case_when (
                        region == 1 ~ "Northeast", 
                        region == 2 ~ "Midwest", 
                        region == 3 ~ "South", 
                        region == 4 ~ "West",
                        TRUE~NA_character_), 
          source_r = case_when (source_r == 1 ~ "ParentsTogether", 
                                source_r == 0 ~ "OtherSources"))

```

```{r, echo=FALSE, message = FALSE, warning = FALSE}
# Extract Relevant Variables
##RL questions - online learning

pt <- master %>%
  select (CaregiverID, StartDate, Week, SurveyType, Source,contains ("PHQ"), contains ("GAD"), STRESS.001, STRESS.002, LONE.001.a, LONE.001.b, contains("CBCL") )

pt$depress_crt= rowMeans(pt[,find_items("PHQ.002.[a-b]$", pt)], na.rm=T)
pt$anxiety_crt = rowMeans(pt[,find_items("GAD2.002.[a-b]$", pt)], na.rm=T)
pt$depress_pre= rowMeans(pt[,find_items("PHQ.001.[a-b]$", pt)], na.rm=T)
pt$anxiety_pre = rowMeans(pt[,find_items("GAD2.001.[a-b]$", pt)], na.rm=T)

pt <- pt %>%
  mutate (depress_crt_r = depress_crt/3*100,
          anxiety_crt_r =anxiety_crt/3*100,
          stress_crt_r = STRESS.002/4*100,
          lonely_crt_r = LONE.001.b/4*100, 
          depress_pre_r = depress_pre/3*100,
          anxiety_pre_r =anxiety_pre/3*100,
          stress_pre_r = STRESS.001/4*100,
          lonely_pre_r = LONE.001.a/4*100)%>%
  rename (fussy_cr1 = CBCL.002.a,
          fussy_cr2 = CBCL.005.a,
          fussy_cr3 = CBCL.008.a,
          fussy_cr4 = CBCL.011.a,
          fussy_cr5 = CBCL.014.a,
          fear_cr1 = CBCL.002.b,
          fear_cr2 = CBCL.005.b,
          fear_cr3 = CBCL.008.b,
          fear_cr4 = CBCL.011.b,
          fear_cr5 = CBCL.014.b, 
          fussy_pr1 = CBCL.001.a,
          fussy_pr2 = CBCL.004.a,
          fussy_pr3 = CBCL.007.a,
          fussy_pr4 = CBCL.010.a,
          fussy_pr5 = CBCL.013.a,
          fear_pr1 = CBCL.001.b,
          fear_pr2 = CBCL.004.b,
          fear_pr3 = CBCL.007.b,
          fear_pr4 = CBCL.010.b,
          fear_pr5 = CBCL.013.b)

fussy_pre_items = c(find_items("fussy_pr", pt))
fear_pre_items = c(find_items("fear_pr", pt))
fussy_crt_items = c(find_items("fussy_cr", pt))
fear_crt_items = c(find_items("fear_cr", pt))

pt$fussy_pre = rowMeans(pt[,fussy_pre_items], na.rm=T)/2*100
pt$fear_pre = rowMeans(pt[,fear_pre_items], na.rm=T)/2*100
pt$fussy_crt = rowMeans(pt[,fussy_crt_items], na.rm=T)/2*100
pt$fear_crt = rowMeans(pt[,fear_crt_items], na.rm=T)/2*100

cp_crt_items = c("fussy_crt", "fear_crt")
cp_pre_items = c("fussy_pre", "fear_pre")

pt$cp_total_crt = rowMeans (pt[, cp_crt_items], na.rm=T)
pt$cp_total_pre = rowMeans (pt[, cp_pre_items], na.rm=T)

pmh_crt_variable = c("depress_crt_r", "anxiety_crt_r", "stress_crt_r", "lonely_crt_r")
pmh_pre_variable = c("depress_pre_r", "anxiety_pre_r", "stress_pre_r", "lonely_pre_r")
pt$pmh_total_crt = rowMeans(pt[, pmh_crt_variable], na.rm = T)
pt$pmh_total_pre = rowMeans(pt[, pmh_pre_variable], na.rm = T)

pt_pre <- pt %>%
  group_by (CaregiverID)%>%
  summarise (pmh_total_pre = mean (pmh_total_pre, na.rm = T), 
             cp_total_pre = mean (cp_total_pre, na.rm = T),)%>%
  ungroup()

pt_rct <- pt %>%
  group_by (CaregiverID)%>%
  filter (Week == max (Week))%>%
  ungroup()%>%
  mutate (pmh_total_crt = as.numeric( pmh_total_crt))%>%
  select (CaregiverID, pmh_total_crt, cp_total_crt)
  
pt_pre = merge (x = pt_pre, y = master_dem, by.x = "CaregiverID", by.y = "CaregiverID")
pt_rct = merge (x = pt_rct, y = master_dem, by.x = "CaregiverID", by.y = "CaregiverID")
pt = merge (x = pt, y = master_dem, by.x = "CaregiverID", by.y = "CaregiverID")

```

# Pre-COVID 
```{r, echo=FALSE, message = FALSE, warning = FALSE}
pt_m <- pt_pre %>%
  group_by (source_r)%>%
  summarise (n = n(),
             parent_problems = mean (pmh_total_pre, na.rm = T), 
             child_problems = mean (cp_total_pre, na.rm = T))%>%
  pivot_longer (cols = c("parent_problems", "child_problems"), names_to = "who", values_to = "mean")

pt_sd <- pt_pre %>%
  group_by (source_r)%>%
  summarise (parent_problems = sd (pmh_total_pre, na.rm = T), 
             child_problems = sd (cp_total_pre, na.rm = T))%>%
  pivot_longer (cols = c("parent_problems", "child_problems"), names_to = "who", values_to = "sd")

pt_smy <- merge (x=pt_m, y=pt_sd)%>%
  mutate (moe = map2_dbl(sd, n, moe.m))

pt_smy %>%
  ggplot(mapping = aes (x = source_r, y = mean, fill = source_r)) +
  geom_bar (stat = "identity", position = position_dodge(1))+
  geom_errorbar(aes(ymin = (mean-moe), 
                    ymax = (mean+moe)),
                    width = .3,
                    position = position_dodge(1)) +
  ggtitle ("Pre-COVID")+
  geom_text(aes(label = round(mean,2)),vjust = -1, color = "black",  position = position_dodge(1))+
  facet_wrap (~who, nrow = 1)+
  theme(axis.text.x = element_blank())

```

# Current - most recent responses
```{r, echo=FALSE, message = FALSE, warning = FALSE}
pt_m <- pt_rct %>%
  group_by (source_r)%>%
  summarise (n = n(),
             parent_problems = mean (pmh_total_crt, na.rm = T), 
             child_problems = mean (cp_total_crt, na.rm = T))%>%
  pivot_longer (cols = c("parent_problems", "child_problems"), names_to = "who", values_to = "mean")

pt_sd <- pt_rct %>%
  group_by (source_r)%>%
  summarise (parent_problems = sd (pmh_total_crt, na.rm = T), 
             child_problems = sd (cp_total_crt, na.rm = T))%>%
  pivot_longer (cols = c("parent_problems", "child_problems"), names_to = "who", values_to = "sd")

pt_smy <- merge (x=pt_m, y=pt_sd)%>%
  mutate (moe = map2_dbl(sd, n, moe.m))

pt_smy %>%
  ggplot(mapping = aes (x = source_r, y = mean, fill = source_r)) +
  geom_bar (stat = "identity", position = position_dodge(1))+
  geom_errorbar(aes(ymin = (mean-moe), 
                    ymax = (mean+moe)),
                    width = .3,
                    position = position_dodge(1)) +
  ggtitle ("Current - most recent responses")+
  geom_text(aes(label = round(mean,2)),vjust = -1, color = "black",  position = position_dodge(1))+
  facet_wrap (~who, nrow = 1)+
  theme(axis.text.x = element_blank())

```


# Trend during COVID
```{r, echo=FALSE, message = FALSE, warning = FALSE}
pt_m <- pt %>%
  group_by (Week, source_r)%>%
  summarise (n = n(),
             parent_problems = mean (pmh_total_crt, na.rm = T), 
             child_problems = mean (cp_total_crt, na.rm = T), 
             )%>%
  pivot_longer (cols = c("parent_problems", "child_problems"), names_to = "who", values_to = "mean")

pt_sd <- pt %>%
  group_by (Week, source_r)%>%
  summarise (parent_problems = sd (pmh_total_crt, na.rm = T), 
             child_problems = sd (cp_total_crt, na.rm = T))%>%
  pivot_longer (cols = c("parent_problems", "child_problems"), names_to = "who", values_to = "sd")

pt_smy <- merge (x=pt_m, y=pt_sd)%>%
  mutate (moe = map2_dbl(sd, n, moe.m))

pt_smy %>%
  ggplot(mapping = aes (x = Week, y = mean, fill = source_r)) +
  geom_point(stat = 'summary') +
  geom_ribbon(aes(ymin = mean-moe, ymax = mean+moe), alpha = .3) +
  geom_line() +
  labs (y = "Mean Problem Level")+
  ggtitle(label = "Trend of changes")+
  facet_wrap(~who, nrow = 2)

```